export const kantoAreas = {
    "areas": [
        {"name": "kanto-route-1-area"},
        {"name": "kanto-route-2-area"},
        {"name": "kanto-route-3-area"},
        {"name": "kanto-route-4-area"},
        {"name": "kanto-route-5-area"},
        {"name": "kanto-route-6-area"},
        {"name": "kanto-route-7-area"},
        {"name": "kanto-route-8-area"},
        {"name": "kanto-route-9-area"},
        {"name": "kanto-route-10-area"},
        {"name": "kanto-route-11-area"},
        {"name": "kanto-route-12-area"},
        {"name": "kanto-route-13-area"},
        {"name": "kanto-route-14-area"},
        {"name": "kanto-route-15-area"},
        {"name": "kanto-route-16-area"},
        {"name": "kanto-route-17-area"},
        {"name": "kanto-route-18-area"},
        {"name": "kanto-sea-route-19-area"},
        {"name": "kanto-sea-route-20-area"},
        {"name": "kanto-sea-route-21-area"},
        {"name": "kanto-route-22-area"},
        {
            "name": "kanto-route-23-area",
            "grid-template-columns": "33% 30.5% 36.5%",
            "grid-template-rows": "",
            "subareas": [{
                "name": "kanto-victory-road-1",
                "grid-area" : {"row": "2", "col" : "2"}
            }]
        },
        {"name": "kanto-route-24-area"},
        {"name": "kanto-route-25-area"},
        {"name": "celadon-city"},
        {"name": "cerulean-city"},
        {"name": "cinnabar-island"},
        {"name": "digletts-cave"},
        {"name": "fuchsia-city"},
        {"name": "mt-moon"},
        {"name": "pallet-town"},
        {"name": "rock-tunnel"},
        {"name": "seafoam-islands"},
        {"name": "cerulean-cave"},
        {"name": "vermilion-city"},
        {"name": "viridian-city"},
        {"name": "viridian-forest"},
        {"name": "power-plant"},
        {"name": "pokemon-tower"},
        {"name": "pokemon-mansion"},
        {"name": "kanto-safari-zone"},
        {"name": "pewter-city"},
        {"name": "lavender-town"},
        {"name": "indigo-plateau"},
        {"name": "saffron-city"},
        {"name": "kanto-victory-road-1"}
    ]
}